### PR TITLE
add GloBI index configuration

### PR DESCRIPTION
**Pull request by jhpoelen**
hi @fonturbel et al. -if you'd like you pollinator catalogue to be indexed by Global Biotic Interactions (GloBI, https://globalbioticinteractions.org), please consider merging this pull request with GloBI indexing configuration.

-jorrit

### CODE REVIEW

**Comment by fonturbel** [comment]
Thanks Jorrit!

**Comment by fonturbel** [comment]
Hi again,

I've accepted the pull request but the indexing fails. I've tried re-running the action many times and always I got an error with code 137 (I don't know what it means). Any suggestions??

**Comment by jhpoelen** [comment]
hi @fonturbel - thanks for accepting the pull request with the GloBI index configuration.

As you noticed, part of the GloBI index configuration is an automated data review for travis-ci.com (has to be enabled manually) and Github Actions (is enabled automatically). This automated data review produced:

(from https://github.com/fonturbel-lab/pollination_catalogue/runs/2420405413#step:4:35 ) -

```
Review of [fonturbel-lab/pollination_catalogue] included:
  - 2269 interaction(s)
  - 393 note(s)
  - 2269 info(s)

[fonturbel-lab/pollination_catalogue] has 393 reviewer note(s):
    288 source taxon name missing
    105 target taxon name missing
```

So, GloBI was able to index 2269 interactions and some review notes were generated. Because there are 393 review notes, a non-0 (0 = OK) return code was generated.

I see these reviews more as a way to start a discussion on getting GloBI to better interpret your dataset. 

So, my question would be: how should GloBI interpret records with missing information on plant names (source taxa) or animal names (target taxa)?

**Comment by jhpoelen** [comment]
I should probably add that the your catalogue will be indexed (at least the 2269 interaction that GloBI was able to extract), but that some review notes remain.

**Pull request merged**
